apps/course/urls.py
from django.urls import path
from . import views


app_name = 'course'

urlpatterns = [
    path('course_index',views.course_index,name='course_index'),
    path('<int:course_id>/',views.course_detail,name='course_detail'),
    path('course_order/<int:course_id>/',views.course_order,name='course_order'),
]

xfz/urls.py
from django.urls import path,include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index,name='index'),
    path('news/',include("apps.news.urls")),
    path('search/',include("haystack.urls")),
    path('cms/',include("apps.cms.urls")),
    path('course/',include("apps.course.urls")),
    path('account/',include("apps.xfzauth.urls")),
    path('ueditor/',include("apps.ueditor.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/course/models.py
#encoding:utf-8

from django.db import models

class CourseCategroy(models.Model):
    name = models.CharField(max_length=100)

class Teacher(models.Model):
    username = models.CharField(max_length=100)
    avatar = models.URLField()
    jobtitle = models.CharField(max_length=100)
    profile = models.TextField()


class Course(models.Model):
    title = models.CharField(max_length=200)
    categroy = models.ForeignKey('CourseCategroy',on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey('Teacher',on_delete=models.DO_NOTHING)
    video_url = models.URLField()
    cover_url = models.URLField()
    price = models.FloatField()
    duration = models.IntegerField()
    profile = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)

class CourseOrder(models.Model):
    course = models.ForeignKey("Course",on_delete=models.DO_NOTHING)
    buyer = models.ForeignKey("xfzauth.User",on_delete=models.DO_NOTHING)
    amout = models.FloatField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    #1代表支付宝 2代表微信
    is_type = models.SmallIntegerField(default=0)
    #默认情况未支付，2代表已支付mi
    status = models.SmallIntegerField(default=1)

apps/course/views.py
#encoding:utf-8

from django.shortcuts import render
from .models import Course,Teacher,CourseOrder
from django.conf import settings
from utils import restful
import time,hmac,os,hashlib
from hashlib import md5
from apps.xfzauth.decorator import xfz_login_required
def course_index(request):
    context = {
        'courses':Course.objects.all()
    }

    return render(request,'course/course.html',context=context)

def course_detail(request,course_id):
    course = Course.objects.get(pk=course_id)
    print(course)
    context = {
        'course':course
    }

    return render(request,'course/course_detail.html',context=context)

def course_token(request):
    # video：是视频文件的完整链接
    file = request.GET.get('video')

    course_id = request.GET.get('course_id')
    expiration_time = int(time.time()) + 2 * 60 * 60


    USER_ID = settings.BAIDU_CLOUD_USER_ID
    USER_KEY = settings.BAIDU_CLOUD_USER_KEY

    # file=http://hemvpc6ui1kef2g0dd2.exp.bcevod.com/mda-igjsr8g7z7zqwnav/mda-igjsr8g7z7zqwnav.m3u8
    extension = os.path.splitext(file)[1]
    media_id = file.split('/')[-1].replace(extension, '')

    # unicode->bytes=unicode.encode('utf-8')bytes
    key = USER_KEY.encode('utf-8')
    message = '/{0}/{1}'.format(media_id, expiration_time).encode('utf-8')
    signature = hmac.new(key, message, digestmod=hashlib.sha256).hexdigest()
    token = '{0}_{1}_{2}'.format(signature, USER_ID, expiration_time)
    return restful.result(data={'token': token})

@xfz_login_required
def course_order(request,course_id):
    course = Course.objects.get(pk=course_id)
    order = CourseOrder.objects.create(course=course, buyer=request.user, status=1, amout=course.price)
    context = {
        'course':course,
        'order':order
    }
    return render(request,'course/course_order.html',context=context)

front/templates/course/course.html
{% extends 'base/front_base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/course/course_index.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/course/course_detail.min.css' %}">
{% endblock %}
{% block title %}
新闻详情
{% endblock %}
{% block main %}
    <div class="main">
        <div class="course-nav">
            <div class="nav-content">
                <h3 class="title">在线课堂</h3>
                <ul class="nav-list">
                    <li ><a class="active" href="#">最新课堂</a></li>
                    <li><a href="#">投资人说</a></li>
                    <li><a href="#">明星案例</a></li>
                    <li><a href="#">创业知识</a></li>
                </ul>
            </div>
        </div>
        <div class="wrapper">
            <ul class="course-lsit">
                {% for course in courses %}
                    <li>
                    <a href="{% url 'course:course_detail' course_id=course.pk %}">
                        <div class="thoubridal-group">
                            <img src="{{ course.cover_url }}" alt="" class="thoubridal">
                        </div>
                        <div class="course-info">
                            <p class="title">{{ course.title }}</p>
                            <p class="author">{{ course.teacher.username }}</p>
                            <p class="price-group">
                                {% if course.price > 0 %}
                                    <span class="price">￥{{ course.price }}</span>
                                {% else %}
                                    <span class="free">免费</span>
                                {% endif %}

                            </p>
                </div>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>

    </div>
{% endblock %}

front/templates/course/course_detail.html
{% extends 'base/front_base.html' %}
{% load static %}
{% block title %}
    新闻详情
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/course/course_detail.min.css' %}">
{% endblock %}
{% block main %}
    <body>
    <div class="main">
        <div class="course-nav">
            <div class="nav-content">
                <h3 class="title">在线课堂</h3>
                <ul class="nav-list">
                    <li><a class="active" href="#">最新课堂</a></li>
                    <li><a href="#">投资人说</a></li>
                    <li><a href="#">明星案例</a></li>
                    <li><a href="#">创业知识</a></li>
                </ul>
            </div>
        </div>
        <div class="wrapper">
            <div class="course-wrapper">
                <div class="course-info">

                    <p class="course-title">{{ course.title }}</p>
                    <div class="price-group">
                        <div class="share-group">
                            <span class="title">分享至：</span>
                            <a class="weixin share-item"></a>
                            <a href="#" class="weibo share-item"></a>
                        </div>
                        <div class="buy-group">
                            {% if course.price > 0 %}
                                <span class="price free">￥{{ course.price }}</span>
                                <a href="{% url 'course:course_order' course_id=course.pk %}" class="buy-button">立即购买</a>
                            {% else %}
                                <span class="price free">免费</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="viedo-group">
                    <span id="video-info" hidden data-video-url="{{ course.video_url }}"
                          data-cover-url="{{ course.cover_url }}"></span>
                    <div id="playercontent"></div>
                </div>
            </div>
            <div class="bottom-wrapper">
                <div class="course-group">
                    <div class="item-group">
                        <p class="item-title">课程讲师</p>
                        <div class="teacher-group">
                            <div class="avoutr-group">
                                <img class="avthor" src="{{ course.teacher.avatar }}" alt="">
                            </div>
                            <div class="teacher-info">
                                <p class="teacher-name">{{ course.teacher.username }}</p>
                                <p class="teacher-desc">{{ course.teacher.jobtitle }}</p>
                            </div>
                        </div>
                        <div class="item-content">
                            <p class="content">
                                {{ course.teacher.profile }}</p>
                        </div>

                    </div>
                </div>
                <div class="recomed-wrapper">
                    <div class="course-title">

                    </div>
                </div>

            </div>

        </div>

    </div>


    </body>
{% endblock %}

front/templates/course/course_order.html
{% extends 'base/front_base.html' %}
{% load static %}
{% block title %}
确认订单
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/comment/heard.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/comment/footer.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/comment/body.min.css' %}">
    <style>
        .table{
            width: 100%;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            background: #eaeaea;
            text-align: center;
        }
        .table{
            border-spacing: 20px;
        }
        .table img{
            width: 120px;
            height: 68px;
            float: left;
        }
        .table .title{
            margin-left: 10px;
        }
        .pay-way label{
            float: right;
            margin-right: 40px;
        }
        .pay-way span{
            border: 1px solid #ccc;
            position: relative;
            top: 20px;
        }
        .pay-way .zfb-btn{
            display: inline-block;
            width: 139px;
            height: 48px;
            cursor: pointer;
            background: url("http://study.163.com/res/images/pay/payList.png");
            background-position: -140px 0;
            background-size: 300% 200%;
            margin-right:20px;
        }
        .pay-way .wx-btn{
            display: inline-block;
            width: 139px;
            height: 48px;
            position: relative;
            cursor: pointer;
        }
        .pay-way .wx-btn img{
            top: 12px;
            left: 16px;
            position: absolute;
        }
        .submit-group{
            overflow: hidden;
            padding: 60px 0;
            margin-right: 40px;
        }
        .submit-btn{
            display: block;
            text-align: center;
            width: 136px;
            height:49px;
            line-height: 49px;
            background: url("http://s.stu.126.net/res/images/pay/payBtns.png?c9b6b849b38cca45b160a96802575ac8") no-repeat 4449px 4449px;
            background-position: 0 -302px;
            border: none;
            cursor: pointer;
            color: #fff;
            font-size: 16px;
            float: right;
        }
        .submit-btn:hover{
            background-position: -139px -302px;
        }
    </style>
    <script>
        $(function () {
            var submitBtn = $("#submit-btn");
            submitBtn.click(function (event) {
                event.preventDefault();
                var goodsname = $("input[name='goodsname']").val();
                var istype = $("input[name='istype']:checked").val();
                var notify_url = $("input[name='notify_url']").val();
                var orderid = $("input[name='orderid']").val();
                var price = $("input[name='price']").val();
                var return_url = $("input[name='return_url']").val();
                xfzajax.post({
                    'url': '/course/course_order_key/',
                    'data': {
                        'goodsname': goodsname,
                        'istype': istype,
                        'notify_url': notify_url,
                        'orderid': orderid,
                        'price': price,
                        'return_url': return_url
                    },
                    'success': function (result) {
                        if(result['code'] === 200){
                            var key = result['data']['key'];
                            var keyInput = $("input[name='key']");
                            keyInput.val(key);
                            $("#pay-form").submit();
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}

{% block main %}
    <div class="main">
        <div class="wrapper">
            <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>商品名称</th>
                    <th>单价(元)</th>
                    <th>小计（元）</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                        <td>
                            <img class="thumbnail" src="{{ course.cover_url }}" alt="">
                        </td>
                    <td align="left">
                        <a href="#">

                            <span class="title">{{ course.title }}</span>
                        </a>
                    </td>
                    <td>{{ course.price }}</td>
                    <td>{{ course.price }}</td>
                </tr>
            </tbody>
        </table>
            <form action="https://pay.bbbapi.com/" method="post" id="pay-form">
                <input type="hidden" name="uid" value="49dc532695baa99e16e01bc0">
                <input type="hidden" name="price" value="{{ course.price }}">
                <input type="hidden" name="notify_url" value="{{ notify_url }}">
                <input type="hidden" name="return_url" value="{{ return_url }}">
                <input type="hidden" name="orderid" value="{{ order.pk }}">
                <input type="hidden" name="orderuid" value="{{ request.user.pk }}">
                <input type="hidden" name="goodsname" value="{{ course.title }}">
                <input type="hidden" name="key" value="">
            <div class="pay-way">
                <label for="istype-wx">
                    <input id="istype-wx" type="radio" name="istype" value="2">
                    <span class="wx-btn">
                        <img src="http://nos.netease.com/test-edu-image/1BD9F69D6760CE1508D2269864AA54F8.png" alt="">
                    </span>
                </label>
                <label for="istype-zfb">
                    <input id="istype-zfb" type="radio" name="istype" value="1" checked>
                    <span class="zfb-btn"></span>
                </label>
                <div style="clear: both;"></div>
            </div>
            <div class="submit-group">
                <input type="submit" value="去支付" id="submit-btn" class="submit-btn">
            </div>
        </form>
        </div>
    </div>
{% endblock %}