apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('<int:news_id>/',views.news_detail,name='news_detail'),
    path('search/',views.search,name='search'),
    path('news_list/',views.news_list,name='news_list'),
    path('public_content/',views.public_content,name='public_content'),
    path('search/',views.search,name='search'),
    path('hot_news/',views.hot_news,name='hot_news'),
    path('more/',views.more,name='more'),




]

xfz/urls.py
from django.urls import path,include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index,name='index'),
    path('news/',include("apps.news.urls")),
    path('search/',include("haystack.urls")),
    path('cms/',include("apps.cms.urls")),
    path('course/',include("apps.course.urls")),
    path('account/',include("apps.xfzauth.urls")),
    path('ueditor/',include("apps.ueditor.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

front/templates/comment/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>授权页面</title>
    <link rel="stylesheet" href="../../dist/css/comment/auth.min.css">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_796312_9rg7q2ll57o.css">
    <script src="../../dist/js/jquery-3.3.1.min.js"></script>
    <script src="../../dist/js/auth.min.js"></script>
</head>
<body>
  <button id="btn">登录/注册</button>
  <div class="mask-wrapper">
      <div class="author-wrapper">
          <div class="close-group">
              <span class="close-btn icon-close iconfont"></span>
          </div>

          <div class="auth-innergroup">
              <div class="scrool-wrapper">
                  <div class="singin-group auth-group">
                      <div class="top-group">
                          <span class="title">请登录</span>
                          <a href="javascript: void (0)" class="swith">立即注册></a>
                      </div>
                      <div class="form-group">
                          <div class="input-group">
                              <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                          </div>
                          <div class="input-group">
                              <input type="password" class="form-control" name="password" placeholder="请输入密码">
                          </div>
                          <lable class="remeber-lable">
                              <input type="checkbox" name="remeber" value="1">
                              记住我
                          </lable>
                          <div class="input-group">
                              <input type="submit" class="subnit-btn" value="立即登录">
                          </div>
                      </div>
                  </div>
                  <div class="singup-group auth-group">
                      <div class="top-group">
                          <span class="title">立即注册</span>
                          <a href="javascript: void (0)" class="swith">立即登录></a>
                      </div>
                      <div>
                          <span>目前不支持注册,没有购买短信服务</span>
                      </div>
                      <div class="form-group">
                          <div class="input-group">
                              <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                          </div>
                          <div class="input-group">
                              <input type="text" class="form-control" name="username" placeholder="用户名">
                          </div>
                          <div class="input-group">
                             <div class="short-group">
                              <input type="text" class="form-control" name="image_catpcha" placeholder="图形验证码">
                            </div>
                            <div class="input-group-addon">
                              <img src="" alt="">
                            </div>
                          </div>
                          <div class="input-group">
                              <input type="password" class="form-control" name="password2" placeholder="密码">
                          </div>
                          <div class="input-group">
                              <div class="short-group">
                                 <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                              </div>
                              <div class="input-group-addon">
                                <span class="ams-captcha-btn">点击发送</span>
                            　</div>
                          </div>
                          <div class="input-group">
                              <input name="siginup-btn" type="submit" class="subnit-btn" value="立即注册">
                          </div>
                      </div>
                  </div>
              </div>

          </div>

      </div>
  </div>
</body>
</html>

front/templates/comment/siderbar.html
{% load news_filters %}

<div class="sider-wrapper">
    <div class="titile-group">
        <span class="title">在线课堂</span>
        <a class="more" href="{% url 'news:more' %}">更多</a>
    </div>
    <div class="advertise-group">
        <a href=""><img src="http://www.xfz.cn/static/build/images/side-gift-banner.png" alt=""></a>
    </div>
    <div class="platform-group">
        <span class="title">关注小饭桌</span>
    </div>
    <div class="focus-group">
        <ul class="left-group">
            <li class="zhihu"><a target="_blank" href="#">小饭桌课堂</a></li>
            <li class="weibo"><a target="_blank" href="#">小饭桌课堂</a></li>
            <li class="toutiao"><a target="_blank" href="#">小饭桌</a></li>
        </ul>
        <div class="right-group">
            <p class="desc">关注小饭桌公众号微信平台xfz001</p>
        </div>
    </div>
    <div class="host-news-group">
        <div class="title-group">
            <span class="title">热门推荐</span>
        </div>
        <ul class="host-list-group">
            {% for news in newes %}
                <li>
                    <div class="left-group">
                        <p class="title">
                            <a href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a>
                        </p>
                        <p class="more">
                            <span class="catgroy">{{ news.categroy.name }}</span>
                            <span class="author-news">{{ news.author.username }}</span>
                            <span class="time">{{ news.pub_tiem|time_since }}</span>
                        </p>
                    </div>
                    <div class="right-group">
                        <a href="#"><img src="{{ news.thumbnail }}" alt=""></a>
                    </div>
                </li>
            {% endfor %}


        </ul>
    </div>
</div>