apps/cms/urls.py
#encoding: utf-8

from django.urls import path
from . import views
from . import course_view as cviews
from . import staff_views as staffviews



app_name = 'cms'

urlpatterns = [
    path('index',views.index,name='index'),
    path('',views.getaroty,name='getaroty'),
    path('write_news/',views.writeNewsView.as_view(),name='write_news'),
    path('news_categroy/',views.news_categroy,name='news_categroy'),
    path('add_news_categroy/',views.add_news_categroy,name='add_news_categroy'),
    path('edit_news_categroy/',views.edit_news_categroy,name='edit_news_categroy'),
    path('delete_news_categroy/',views.delete_news_categroy,name='delete_news_categroy'),
    path('banners/',views.banners,name='banners'),
    path('upload_file/',views.upload_file,name='upload_file'),
    path('qntoken/',views.qntoken,name='qntoken'),
    path('add_banners/',views.add_banners,name='add_banners'),
    path('banners_list/',views.banners_list,name='banners_list'),
    path('delete_banner/',views.delete_banner,name='delete_banner'),
    path('edit_banner/',views.edit_banner,name='edit_banner'),
    path('news_list/',views.NewsListView.as_view(),name='news_list'),
    path('news_list/',views.NewsListView.as_view(),name='news_list'),
    path('edit_news/',views.EditNewsView.as_view(),name='edit_news'),
    path('dasbaord/',views.dasbaord,name='dasbaord'),


]

urlpatterns +=[
    path('pubcourse/',cviews.pubCourse.as_view(),name='pubcourse'),

]

urlpatterns +=[
    path('staffs/',staffviews.staffs_view,name='staffs'),
    path('add_staffs/',staffviews.AddStaffsView.as_view(),name='add_staffs'),
    path('delete_staffs/',staffviews.delete_staffs,name='delete_staffs'),


]

apps/course/urls.py
from django.urls import path
from . import views


app_name = 'course'

urlpatterns = [
    path('course_index',views.course_index,name='course_index'),
    path('<int:course_id>/',views.course_detail,name='course_detail'),
    path('course_order/<int:course_id>/',views.course_order,name='course_order'),
]

apps/xfzauth/urls.py
#encoding: utf-8

from django.urls import path
from . import  views

app_name = "xfzauth"

urlpatterns = [
    path("login/",views.login_view,name='login'),
    path("logout/",views.logout_view,name='logout'),
    path("image_captcha/",views.image_captcha,name='image_captcha'),
    path("sms_captcha/",views.sms_captcha,name='sms_captcha'),
    path("register/",views.register,name='register'),
]

xfz/urls.py
from django.urls import path,include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index,name='index'),
    path('news/',include("apps.news.urls")),
    path('search/',include("haystack.urls")),
    path('cms/',include("apps.cms.urls")),
    path('course/',include("apps.course.urls")),
    path('account/',include("apps.xfzauth.urls")),
    path('ueditor/',include("apps.ueditor.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

front/templates/base/front_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="/static/images/xfz.ico" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/comment/auth.min.css' %}">
    <link rel="stylesheet" href="http:////at.alicdn.com/t/font_796312_9rg7q2ll57o.css">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/front_base.min.js' %}"></script>
    {% block head %}

    {% endblock %}
</head>
<body>
<header class="header">
    <div class="content">
        <div class="logo-box">
            <a href="/"></a>
        </div>
        <ul class="nav">
            <li><a href="/">创业资讯</a></li>
            <li><a href="{% url 'course:course_index' %}">创业课堂</a></li>
            <li><a href="#">付费资讯</a></li>
            <li><a href="/search/">搜索</a></li>
        </ul>
        <div class="auth-box">
            {% csrf_token %}
            <i class="icon-person iconfont"></i>
            {% if user.is_authenticated %}
                <a href="#" class="authenticated-name">{{ user.username }}</a>
                <div class="user-more-box">
                    <i class="triangle"></i>
                    {% if user.is_staff %}
                        <a href="{% url 'cms:index' %}">管理系统</a>
                    {% endif %}
                    <a href="{% url 'xfzauth:logout' %}">退出登录</a>
                </div>
            {% else %}
                <a href="#" class="signin-btn">登录/</a>
                <a href="#" class="signup-btn">注册</a>
            {% endif %}
        </div>

    </div>
</header>
{% block main %}{% endblock %}
<footer class="footer">
    <div class="top-group">
        <div class="top-inner-group">
            <div class="logo-box">
            </div>
            <div class="detail-group">
                <div class="line1">
                    <ul class="links">
                        <li><a href="/">关于小圆桌</a></li>
                        <li><a href="{% url 'course:course_index' %}">创业课堂</a></li>
                        <li><a href="#">寻求报道</a></li>
                        <li><a href="#">创业礼包</a></li>
                    </ul>
                    <div class="about-us">
                        <span class="title">关于我们:</span>
                        <div class="socail">
                            <li class="weixin">
                                <div class="wx-qrcode"></div>
                                <a href="#" class="text">xfz001</a>
                            </li>
                            <li class="weibo"><a href="#" class="text">
                                小圆桌创业课堂
                            </a></li>
                        </div>
                    </div>
                </div>
                <div class="line2">
                    <p class="address">
                        地址:广东省深圳市龙岗区天安云谷B座7楼
                    </p>
                    <p class="content">联系方式：400-910-1090(工作日10点-18点)</p>
                </div>

            </div>
        </div>
    </div>
    <div class="bottom-group">
        ©2018 北京子木投资顾问有限公司 京ICP备15051289号 | 增值电信业务经营许可证：京B2-20170574
    </div>
</footer>
<div class="mask-wrapper">
    <div class="author-wrapper">
        <div class="close-group">
            <span class="close-btn icon-close iconfont"></span>
        </div>

        <div class="auth-innergroup">
            <div class="scrool-wrapper">
                <div class="singin-group auth-group">
                    <div class="top-group">
                        <span class="title">请登录</span>
                        <a href="javascript: void(0)" class="switch">立即注册></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="telephone" placeholder="请输入手机号码">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password" placeholder="请输入密码">
                        </div>
                        <lable class="remeber-lable">
                            <input type="checkbox" name="remeber" value="1">
                            记住我
                        </lable>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" value="立即登录">
                        </div>
                    </div>
                </div>
                <div class="singup-group auth-group">
                    <div class="top-group">
                        <span class="title">立即注册</span>
                        <a href="javascript: void (0)" class="switch">立即登录></a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                        </div>
                        <div class="input-group">
                            <input type="text" class="form-control" name="username" placeholder="用户名">
                        </div>
                        <div class="input-group">
                            <div class="short-group">
                                <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                            </div>
                            <div class="input-group-addon">
                                <img class="image-captcha-btn" src="{% url 'xfzauth:image_captcha' %}" alt="">
                            </div>
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password1" placeholder="密码">
                        </div>
                        <div class="input-group">
                            <input type="password" class="form-control" name="password2" placeholder="确认密码">
                        </div>
                        <div class="input-group">
                            <div class="short-group">
                                <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
                            </div>
                            <div class="input-group-addon">
                                <span class="sms-captcha-btn">点击发送</span>
                                　
                            </div>
                        </div>
                        <div class="input-group">
                            <input  name="siginup-btn" type="submit" class="submit-btn" value="立即注册">
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>
</body>
</html>